spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.115.226.171:3306/universe
        username: root
        password: 123
    session:
        timeout: 86400
server:
    address: 0.0.0.0